### ISSUE TITLE
🔧 config: AWS RDS 사용

### ISSUE THREAD

**Issue by Nbo-KimHyeongSeob** [Team-Seollem/seollem-be#12]
### 📌 작업 내용

- 기존 ec2 상에 실행되던 mysql 을 제거하고, AWS 의 RDS 에서 mysql 인스턴스를 생성하여 사용한다.

### ✅ Todo

- [x] RDS 인스턴스 생성
- [x] 기존 mysql 데이터를 RDS 인스턴스로 replication
- [x] 서버 앱과 RDS 인스턴스 연동
- [x] 기존 mysql 제거
- [x] (기존 버그) spring-cloud-starter-aws 관련 에러 해결 : `com.amazonaws.util.EC2MetadataUtils : Unable to retrieve the requested metadata (/latest/meta-data/instance-id). Failed to connect to service endpoint:`
