### ISSUE TITLE
✨ feat: Abandon 책 조회 기능 수정

### ISSUE THREAD

**Issue by Nbo-KimHyeongSeob** [Team-Seollem/seollem-be#37]
### 📌 작업 내용

- Abandon 책 조회 기능이 현재는 페이지네이션으로 응답하지만, 요청한 `년도, 월` 에 따라 응답하도록 수정한다.

### ✅ Todo

- [x] 요청으로 `년도, 월` 을 받을 수 있도록 수정
- [x] JPA 쿼리 수정하여 `년도, 월`에 따라 데이터 추출
- [x] 페이지네이션 그대로 유지하고 데이터 응답
