### ISSUE TITLE
🐛 fix: Book 엔티티의 memoCount, Memo 엔티티의 memoLikesCount 로직 검토

### ISSUE THREAD

**Issue by Nbo-KimHyeongSeob** [Team-Seollem/seollem-be#44]
### 📌 작업 내용

- Book 엔티티의 memoCount, Memo 엔티티의 memoLikesCount 로직이 제대로 구현된건 지 검토하고, 데이터 정합성을 지키도록 구현한다.
- 각 Count 로직은, 해당되는 자식 테이블에 데이터가 추가될 때마다 추가 또는 삭제되는 방식이다. 여기에는 두가지 오류가 있다. 해당 엔티티의 최초부터 도입되지 않았다면 카운트가 정확하지 않다. DB 가 직접 수정되면 카운트가 정확하지 않다. 즉, 데이터 정합성을 보장할 수 없는 것이다.
- 따라서 매번 자식 테이블의 데이터 개수를 카운트하는 것이 가장 정확한데, 이는 성능에 부담을 줄 수 있기 때문에 검토가 필요하다.
- Memo 엔티티의 memoLikesCount 로직은 구현자도 설명하지 못하고 있으므로 새롭게 구현해야 한다.

### ✅ Todo

- [x] Book, Memo 엔티티에서 각 필드를 삭제한다.
- [x] DB 에서 자식 테이블의 개수를 카운트한 값을 가져오는 로직을 구현한다.
- [x] 두 필드가 사용되던 API을 찾아 수정한다.
- Book 의 memoCount
  - 책 Library 조회
  - 메모가 존재하는 책 조회
  - 책 상세페이지 조회
- Memo 의 memoLikesCount
  - 책 상세페이지 조회
  - 책의 메모 조회
  - 메모 등록 -> 메모를 처음 등록하는데 memoLikesCount 가 의미가 없으므로 제외함.
  - 메모 수정
- [x] Rest Docs 코드도 모두 변경한다.
- [x] ERD 변경한다.
